packages:
  - web
  - worker

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false

onlyBuiltDependencies:
  - argon2
  - esbuild
  - sharp
  - unrs-resolver
  - "@parcel/watcher"
  - "@swc/core"
